server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
#Configuracion de scrapper para logs de esta maquina
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

#Configuracion para docker logs
#scrape_configs:
#  - job_name: 'docker-logs'
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: docker
#          __path__: /var/log/*log
